### ISSUE TITLE
babel errors

### ISSUE THREAD

**Issue by Morriz** [IanVS/prettier-plugin-sort-imports#34]
**Your Environment**

-   **Prettier version**: 2.7.0
-   **node version**: 16.5
-   **package manager**: npm@7
-   **IDE**: VScode

**Describe the bug**

I consistently get errors since a while:
```
["INFO" - 2:00:36 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 2:00:36 PM] Prettier Options:
{
  "filepath": "/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/src/components/hook-form/RHFSwitch.tsx",
  "parser": "typescript",
  "semi": false,
  "trailingComma": "all",
  "singleQuote": true,
  "printWidth": 120,
  "jsxSingleQuote": true,
  "importOrderMergeDuplicateImports": true,
  "importOrderParserPlugins": [
    "typescript",
    "classProperties",
    "decorators-legacy"
  ]
}
["ERROR" - 2:00:36 PM] Error formatting document.
["ERROR" - 2:00:36 PM] Unexpected token, expected "," (8:24)
   1 | import { SwitchElement, SwitchElementProps } from 'react-hook-form-mui'
   2 | import { FieldValues } from 'react-hook-form'
   3 |
   4 | export default function RHFSwitch<TFieldValues extends FieldValues>({
   5 |   disabled,
   6 |   ...other
   7 | }: SwitchElementProps<TFieldValues>) {
   8 |   return <SwitchElement {...other} validation={{ disabled }} disabled={disabled} />
   9 | }
  10 |
SyntaxError: Unexpected token, expected "," (8:24)
   1 | import { SwitchElement, SwitchElementProps } from 'react-hook-form-mui'
   2 | import { FieldValues } from 'react-hook-form'
   3 |
   4 | export default function RHFSwitch<TFieldValues extends FieldValues>({
   5 |   disabled,
   6 |   ...other
   7 | }: SwitchElementProps<TFieldValues>) {
   8 |   return <SwitchElement {...other} validation={{ disabled }} disabled={disabled} />
   9 | }
  10 |
	at instantiate (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:72:32)
	at constructor (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:358:12)
	at Parser.raise (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:3336:19)
	at Parser.unexpected (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:3374:16)
	at Parser.expect (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:4003:28)
	at Parser.tsParseDelimitedListWorker (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:8523:14)
	at Parser.tsParseDelimitedList (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:8492:25)
	at Parser.tsParseBracketedList (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:8545:25)
	at Parser.tsParseTypeParameters (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:8682:24)
	at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10728:29
	at Parser.tryParse (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:4012:20)
	at Parser.parseMaybeAssign (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10725:24)
	at Parser.parseExpressionBase (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12254:23)
	at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12248:39
	at Parser.allowInAnd (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14343:16)
	at Parser.parseExpression (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12248:17)
	at Parser.parseReturnStatement (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15055:28)
	at Parser.parseStatementContent (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14694:21)
	at Parser.parseStatementContent (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10354:18)
	at Parser.parseStatement (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14640:17)
	at Parser.parseBlockOrModuleBlockBody (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15283:25)
	at Parser.parseBlockBody (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15274:10)
	at Parser.parseBlock (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15258:10)
	at Parser.parseFunctionBody (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:13948:24)
	at Parser.parseFunctionBodyAndFinish (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:13932:10)
	at Parser.parseFunctionBodyAndFinish (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10066:11)
	at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15433:12
	at Parser.withSmartMixTopicForbiddingContext (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14320:14)
	at Parser.parseFunction (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15432:10)
	at Parser.parseExportDefaultExpression (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15990:19)
	at Parser.parseExportDefaultExpression (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10306:18)
	at Parser.parseExport (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15902:31)
	at Parser.parseExport (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10284:20)
	at Parser.parseStatementContent (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14756:27)
	at Parser.parseStatementContent (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10354:18)
	at Parser.parseStatement (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14640:17)
	at Parser.parseBlockOrModuleBlockBody (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15283:25)
	at Parser.parseBlockBody (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15274:10)
	at Parser.parseProgram (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14558:10)
	at Parser.parseTopLevel (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14545:25)
	at Parser.parse (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:16508:10)
	at Parser.parse (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:11151:18)
	at Object.parse (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:16560:38)
	at Object.preprocessor [as preprocess] (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@ianvs/prettier-plugin-sort-imports/lib/src/preprocessor.js:20:24)
	at Object.parse (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/prettier/index.js:7357:25)
	at coreFormat (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/prettier/index.js:8672:18)
	at formatWithCursor2 (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/prettier/index.js:8864:18)
	at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/prettier/index.js:39174:12
	at Object.format (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/prettier/index.js:39188:12)
	at t.default.format (/Users/Morriz/.vscode/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:13489)
	at async t.PrettierEditProvider.provideEdits (/Users/Morriz/.vscode/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:10196)
	at async $.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:45865)
["INFO" - 2:00:36 PM] Formatting completed in 0.005ms.
```

**To Reproduce**

```ts
import { SwitchElement, SwitchElementProps } from 'react-hook-form-mui'
import { FieldValues } from 'react-hook-form'

export default function RHFSwitch<TFieldValues extends FieldValues>({
  disabled,
  ...other
}: SwitchElementProps<TFieldValues>) {
  return <SwitchElement {...other} validation={{ disabled }} disabled={disabled} />
}
```
Even using a simple snippet like this:
```ts
export default function ok() {
  return (<>{'ok'}</>)
}
```
produces babel errors:
```
["INFO" - 2:05:22 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 2:05:22 PM] Prettier Options:
{
  "filepath": "/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/src/components/hook-form/RHFSwitch copy.tsx",
  "parser": "typescript",
  "semi": false,
  "trailingComma": "all",
  "singleQuote": true,
  "printWidth": 120,
  "jsxSingleQuote": true,
  "importOrderMergeDuplicateImports": true,
  "importOrderParserPlugins": [
    "typescript",
    "classProperties",
    "decorators-legacy"
  ]
}
["ERROR" - 2:05:22 PM] Error formatting document.
["ERROR" - 2:05:22 PM] Type parameter list cannot be empty. (2:10)
  1 | export default function ok() {
  2 |   return (<>{'ok'}</>)
  3 | }
  4 |
SyntaxError: Type parameter list cannot be empty. (2:10)
  1 | export default function ok() {
  2 |   return (<>{'ok'}</>)
  3 | }
  4 |
	at instantiate (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:72:32)
	at constructor (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:358:12)
	at Parser.raise (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:3336:19)
	at Parser.tsParseTypeParameters (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:8685:12)
	at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10728:29
	at Parser.tryParse (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:4012:20)
	at Parser.parseMaybeAssign (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10725:24)
	at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12276:39
	at Parser.allowInAnd (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14349:12)
	at Parser.parseMaybeAssignAllowIn (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12276:17)
	at Parser.parseParenAndDistinguishExpression (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:13402:28)
	at Parser.parseExprAtom (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12973:23)
	at Parser.parseExprSubscripts (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12645:23)
	at Parser.parseUpdate (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12624:21)
	at Parser.parseMaybeUnary (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12595:23)
	at Parser.parseMaybeUnary (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10797:20)
	at Parser.parseMaybeUnaryOrPrivate (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12389:61)
	at Parser.parseExprOps (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12396:23)
	at Parser.parseMaybeConditional (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12366:23)
	at Parser.parseMaybeAssign (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12318:21)
	at Parser.parseMaybeAssign (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10720:20)
	at Parser.parseExpressionBase (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12254:23)
	at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12248:39
	at Parser.allowInAnd (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14343:16)
	at Parser.parseExpression (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:12248:17)
	at Parser.parseReturnStatement (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15055:28)
	at Parser.parseStatementContent (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14694:21)
	at Parser.parseStatementContent (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10354:18)
	at Parser.parseStatement (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14640:17)
	at Parser.parseBlockOrModuleBlockBody (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15283:25)
	at Parser.parseBlockBody (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15274:10)
	at Parser.parseBlock (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15258:10)
	at Parser.parseFunctionBody (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:13948:24)
	at Parser.parseFunctionBodyAndFinish (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:13932:10)
	at Parser.parseFunctionBodyAndFinish (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10066:11)
	at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15433:12
	at Parser.withSmartMixTopicForbiddingContext (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14320:14)
	at Parser.parseFunction (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15432:10)
	at Parser.parseExportDefaultExpression (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15990:19)
	at Parser.parseExportDefaultExpression (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10306:18)
	at Parser.parseExport (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15902:31)
	at Parser.parseExport (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10284:20)
	at Parser.parseStatementContent (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14756:27)
	at Parser.parseStatementContent (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:10354:18)
	at Parser.parseStatement (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14640:17)
	at Parser.parseBlockOrModuleBlockBody (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15283:25)
	at Parser.parseBlockBody (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:15274:10)
	at Parser.parseProgram (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14558:10)
	at Parser.parseTopLevel (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:14545:25)
	at Parser.parse (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:16508:10)
	at Parser.parse (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:11151:18)
	at Object.parse (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@babel/parser/lib/index.js:16560:38)
	at Object.preprocessor [as preprocess] (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/@ianvs/prettier-plugin-sort-imports/lib/src/preprocessor.js:20:24)
	at Object.parse (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/prettier/index.js:7357:25)
	at coreFormat (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/prettier/index.js:8672:18)
	at formatWithCursor2 (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/prettier/index.js:8864:18)
	at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/prettier/index.js:39174:12
	at Object.format (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-cloud/node_modules/prettier/index.js:39188:12)
	at t.default.format (/Users/Morriz/.vscode/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:13489)
	at async t.PrettierEditProvider.provideEdits (/Users/Morriz/.vscode/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:10196)
	at async $.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:45865)
["INFO" - 2:05:22 PM] Formatting completed in 0.006ms.
```

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```yaml
semi: false
trailingComma: all
singleQuote: true
printWidth: 120
jsxSingleQuote: true
importOrderMergeDuplicateImports: true
importOrderParserPlugins:
  - typescript
  - classProperties
  - decorators-legacy
```

**Comment by Morriz** [comment]
of course removing this plugin makes the errors go away...now why is babel at play here?

**Comment by IanVS** [comment]
Babel is used to parse the code into an AST, which is then operated on to re-arrange imports, much like a codemod.  

What version of typescript are you using, and can you run `npm ls @babel/core` to see what version is installed?  You can try an `npm upgrade @babel/core` (or the yarn equivalent) to get the latest and update your lockfile.

**Comment by blutorange** [comment]
Do we have any tests for *.tsx files? (since it seems related to JSX and I don't see any tests for that)

**Comment by Morriz** [comment]
I don't have `@babel/core` installed. If it is a dependency of this plugin than it was the latest that came with today's install of `v3.4.2`.

**Comment by Morriz** [comment]
I went back to the original `eslint-plugin-import` and don't suffer from it sorting 'reflect-metadata' to the wrong location, so I am happy.

**Comment by IanVS** [comment]
It is indeed a dependency of the plugin. To help us troubleshoot, would you mind sharing the output of the command I gave above?

**Comment by IanVS** [comment]
Sorry, what issue did you have with `reflect-metadata`?

**Comment by Morriz** [comment]
before I had issues with imports not ordering correctly, like:
```ts
import 'reflect-metadata'
```
going down. But that does not seem to be the case anymore. Anyway, I uninstalled this plugin so I don't have `@babel/core` anymore. If you are interested in the version of it, then I suggest installing this plugin and checking the lock file ;)
